version: "3"

services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./src/public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    volumes:
      - ./src:/var/www/html

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
